### ISSUE TITLE
Arch Linux build error in fingerprint.c

### ISSUE THREAD

**Issue by ghost** [twstrike/libotrv4#181]
On Arch Linux I can't succesfully build from git master anymore lately.

$ pacman -Q glib2 libgcrypt libgoldilocks libotr libsodium
glib2 2.58.1+67+g17519e039-1
libgcrypt 1.8.4-1
libgoldilocks-git 644.045bec4-1
libotr 4.1.1-2
libsodium 1.0.16-1

PKGBUILD used: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libotr-ng-git

Anything after https://github.com/otrv4/libotr-ng/commit/7d661831124cc2e0b7588ff5ee605e2371d6633c shows an error related to fingerprint.c:
...
fingerprint.c: In function ‘otrng_fingerprint_forget’:
fingerprint.c:197:20: error: ‘prev’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         prev->next = c;
...

Full build log: https://ptpb.pw/3jC-.log

I did notice that libotr-ng is going through changes related to https://github.com/otrv4/libotr-ng/issues/164, so this might be a temporary issue. Nevertheless, I thought you might want to be aware of this. Please feel free to ask if there's any other info I can provide here.

Regards.

**Comment by olabini** [comment]
Hey, sorry about that. It was a small mistake that I have just fixed in the last push. Thanks for reporting it!

**Comment by ghost** [comment]
@olabini Follow-up. Thanks for the speedy fix. The build is still not working here though:
...
units/test_messaging.c: In function ‘read_full_file’:
units/test_messaging.c:488:3: error: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Werror=unused-result]
   fread(buffer, fsize, 1, fp);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
...
Full build log: https://ptpb.pw/eIhV.log

**Comment by olabini** [comment]
Ah, interesting. I'll fix in a second - I just have to sort out a few small memory leaks.

**Comment by olabini** [comment]
Hmm, so my compiler doesn't find this problem, even when turning on that flag. However, I've fixed it now - hopefully there are no more problems, but do let us know!

**Comment by ghost** [comment]
@olabini Odd indeed. But, good news, the build is now working fine again. Really appreciated!

**Comment by olabini** [comment]
Thanks! We appreciate the reports.
